language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  app: flask-template-dev
  api_key:
    secure: reng+RburiVKZnM/R3UINorkFuM9YL7ZFp7DJxNDzHkusotSmY3G/XlFW+UOiZt6ZrkP/nJImzUaTemYnRdc+pC+OKiBZtp/Lal07HDyTXJIFND6tiRvjQOnO52D4EnFeaqBYDQ+GdBUrVokF4JCT4Ar8+pGR1Zd+TUSQlDLSQHvoU37aXHVxCts8M2n2DkKwBTnwwBMgifJTZSU56AHblhcGDnyboDBpybNq3i+Ptlmz537QQcdO7dzao25AT8ala1XMq6asfTes90cgvVgj2YISbQzqMITY8e3I2jW5dY3Dnjkmo1OkNflYk4UJ2rByBGCl/4f8qPPoxwpVWzRwuLjvVutBs9RI9RhMSHwzWWlY3CTlCr/N3tjDR4nZM+c2k4PWXgSNay/QdpjS90zQkHQumqpLKNSMMG7l9I/SRzIR83Kz9/S8w4WhOfjWLipxEFPDODuWC+XZe5r0yiP8iyyAmYE78Nby71lKOo+5NbuG/FsdwH74UhK1DCUSLZNb49x4CJ8gINR93qnSFz6Ei07zrY9GGN7F2uigKsK9T8Vgkmm8F4X/fiBBGVgCdl5piHmpe3Q6P01pXgnOqjjxxecSQI9ZrUu9+OLazJ/tbyeMeO+Fj/YNTzZK4Qg5pLzJ4+wC+2ol5S3fGNpFdY74/ratRhpRHAbqk4N4ZUAYPU=
