branches:
  only:
  - master
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - pytest
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - ./scripts/db/init
deploy:
  provider: heroku
  app: flask-template-dev
  api_key:
    secure: HsPqGK6FcEmngSUJjRWlxSWBNRrewzAAwtB+3eUPzZcamfUqQm2im0SshUVrRavAZp8ZwEYoP5chiCpvOqKU5mFZVletLvbBG2hMqG6QcTv93D1gyfycbshx/DkmU1iMDWQRWMek16/3OL002oxYBToYTWP5WO1c0AionOg47R+xi4DItW3OVltIM7NoLEZDRY2TFeVgtSCpe2Gj/k/swK/G9JnqBccYDi0iDOKapjFiRkXdignqGfkFEy/p10MaSBY+2Ouzsl78Dw9/rVHEPwq6JPjCDqi/6VaJjUaxetVl71EURiBKaRun30GZkgMYGZ5fWboW/P/EI52XuC2UC5EsGmOfHGHCjWq2jI5tmbNo1OCNY7xpmo9m7QKWzusrNt1z1Beu9/4nUUKXU0hVJvkS9jdAsOk6FMvVjow0XDCM7KCH3VvYBtA4tu8XtehfabnZDZjTnWTZveviPvpm/eT5xWPr7NkQkWW7ntnq71DOeJ9GejraVf7MQoGo6ZCFC3oko0/x9w2ahIlNYKlyBgl8fxC8GaDwgnQvhGhu/1mUuCFhtuXNDNvBpwCY0rweMn5Y5kdeuIHXHTQRoZzXQqb6h+N2hkI6IIqHNP+d4T0/Ot/e/S/X9V0MGB2UWa6B0H6jmz+sGACsCYdlsHcbzpxbLh9Cw29pHhpUCvOiFLQ=
