branches:
  only:
    - master
    - "/\\d+\\.\\d+\\.\\d+/"
language: python
python:
  - '3.8'
install:
  - pip install -r requirements.txt
script:
  - pytest
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - "./scripts/db/init"
  - psql flask-template-db -f ./scripts/db/init-user.sql
deploy:
  on:
    repo: ethanphunter/Flask_Template
    tags: true
    all_branches: true
  provider: heroku
  app: flask-template-dev
  api_key:
    secure: XUdgEyKrgojal/HSj/yoBCAp+TkPN43CgY8XYeH1q3rr5UdwmZCh820RgqulcxFulxKRzhDCw+vdBs6RjG53+nayZrerPxMYqvhJyDCoiL6oa8FT5xvChndLeS3oMUNi1DkjeGluObZwcaVFJKDlncITDAgCHRVC6W/XOq5yBdG/CuHChcOdCJB7CZ6atmcFOKp9VmBg9ev7/JZj/cCQeIifj6u9leGH66LEPdiPa/SA+drcoe8KfCDLwhxwT6zNLy6UzR1NcRUH1pm5/Dvj3ZgafYWjGBFFGrnFfpgDvxKLCU9yf0oQMSlKS/gVCIX3Ys1plogmJ9gXVoxeEgQtFWBotVnEPVjvKUaLPQ44AqaJ4oSEcwfQJjnI8SBJu8wEEfPhAVVtloFDTlLpk5I/Gw4ANZ+MirkfjMmY55YZhkeukuQ8VTO20ht1+BAV+Q+nY4jEXrbR+VCbeKrgBC3WtgYEml8eDAIwAGCpDs0czpv1nZQH836XCyPodAVmJzfp1FQAkOt5U09FZOsPu8Yu5iubSIsj/PPEb0/B/iRfMbWMl+2clME876FnK8kx88niYaKzCjbngS2+BGpJ7cTSjT2xI1LtgnrrqP+RlmfQOgZuUsA67zwVqD2bANgOvTeCXyAflPP97uWSpjHVVxqHZcGIhJJbaGhnui8gNrZup6k=
